### ISSUE TITLE
Recommendations not working

### ISSUE THREAD

**Issue by vekst** [Aux/Basset#1]
Basically anything related to recommending/recommendations stops working (command times out I guess?) once a user gathers even a little amount of songs listened to. Worked when I had listened to a single song but hasn't since, Basset types but nothing comes out.

**Comment by Aux** [comment]
The actual issue is that spotify tokens expire after an hour and Basset doesn't properly refresh those tokens. This is solved in an update I'm sitting on and should be ready and pushed to release tomorrow (July 5th).

**Comment by vekst** [comment]
Oh sweet, can't wait! Thanks for responding.
